
function generateCode() {

    const operation = document.getElementById("operation").value;
    const x = parseFloat(document.getElementById("x").value);
    const y = parseFloat(document.getElementById("y").value);
    const diameter = parseFloat(document.getElementById("diameter").value);
    const depth = parseFloat(document.getElementById("depth").value);

    let gcode = "";

    gcode += "%\n";
    gcode += "(Generated by CNC Code Generator)\n";
    gcode += "G21\n";          // Metric units
    gcode += "G17 G90 G40\n";
    gcode += "G0 Z10.0\n";

    if (operation === "Circle") {

        const radius = diameter / 2;

        gcode += `G0 X${(x + radius).toFixed(3)} Y${y.toFixed(3)}\n`;
        gcode += "G1 Z0.0 F200\n";
        gcode += `G1 Z${depth.toFixed(3)} F100\n`;

        gcode += `G2 I${(-radius).toFixed(3)} J0.000 F300\n`;

        gcode += "G0 Z10.0\n";
    }

    else if (operation === "Drilling") {

        gcode += `G0 X${x.toFixed(3)} Y${y.toFixed(3)}\n`;
        gcode += `G81 Z${depth.toFixed(3)} R2.000 F150\n`;
        gcode += "G80\n";
        gcode += "G0 Z10.0\n";
    }

    else if (operation === "Facing") {

        gcode += "(Facing cycle coming soon)\n";
    }

    else if (operation === "Rectangle Pocket") {

        gcode += "(Rectangle Pocket coming soon)\n";
    }

    gcode += "M30\n";
    gcode += "%";

    document.getElementById("output").value = gcode;
}
