function generateGCode() {
    // Read values from the form
    const width = parseFloat(document.getElementById("width").value);
    const height = parseFloat(document.getElementById("height").value);
    const depth = parseFloat(document.getElementById("depth").value);
    const feed = parseFloat(document.getElementById("feed").value);

    // Validate inputs
    if (
        isNaN(width) ||
        isNaN(height) ||
        isNaN(depth) ||
        isNaN(feed)
    ) {
        alert("Please fill in all fields.");
        return;
    }

    // Build G-code
    let gcode = "";
    gcode += "%\n";
    gcode += "(Generated by CNC Code Generator)\n";
    gcode += "G21\n";          // Metric
    gcode += "G17\n";          // XY Plane
    gcode += "G90\n";          // Absolute positioning
    gcode += "G54\n";
    gcode += "\n";
    gcode += "M3 S12000\n";
    gcode += "G0 Z5.000\n";
    gcode += "G0 X0 Y0\n";
    gcode += "\n";
    gcode += `G1 Z-${depth.toFixed(3)} F300\n`;
    gcode += `G1 X${width.toFixed(3)} Y0.000 F${feed}\n`;
    gcode += `G1 X${width.toFixed(3)} Y${height.toFixed(3)}\n`;
    gcode += `G1 X0.000 Y${height.toFixed(3)}\n`;
    gcode += "G1 X0.000 Y0.000\n";
    gcode += "\n";
    gcode += "G0 Z5.000\n";
    gcode += "M5\n";
    gcode += "M30\n";
    gcode += "%";

    // Display output
    document.getElementById("output").value = gcode;
}
